Repository inex/IXP-Manager, pull requests merged in 2020-05, with the labels that each got.

#644 Allow a customer to add an inital MAC address. Resolves #643
  resources/views/customer/overview-tabs/ports/port.foil.php
Labels: Improvement, Pending CLA

#645 [NF] Implements #636 - Display MD5 password for RS/RC peering sessions on customer backend
  resources/views/customer/overview-tabs/ports/port.foil.php
Labels: Improvement, Pending CLA

#648 [NF] Implements #642 - Logging for failed auth events
  app/Listeners/Auth/LoginFailed.php
  app/Providers/EventServiceProvider.php
Labels: Improvement, Pending CLA

#625 [NF] update-dns-from-ixp-manager.sh sample script could warn on zonefile errors
  tools/runtime/dns-arpa/update-dns-from-ixp-manager.sh
Labels: Pending CLA

#650 [BF] Rack field in patch panel LoA verification page is blank
  resources/views/patch-panel-port/verify-loa.foil.php
Labels: Bug
